import React, { useMemo } from "react";
import { RepeatWrapping } from "three";
import { Html, useGLTF, useTexture } from "@react-three/drei";
import UseMaterialType from "../Utils/materialTypeHook";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/roomGlb.glb");

  const setSelectedMaterialType = UseMaterialType((s) => s.setMaterialType);
  const getSelectedMaterialType = UseMaterialType((s) => s.materialType);

  const getFloorImageUrl = UseMaterialType((s) => s.floorTextureUrl);
  const getWallImageUrl = UseMaterialType((s) => s.wallTextureUrl);

  let floorImage = useTexture(getFloorImageUrl);
  let wallImage = useTexture(getWallImageUrl);

  useMemo(() => {
    floorImage.wrapS = RepeatWrapping;
    floorImage.wrapT = RepeatWrapping;
    floorImage.repeat.set(4, 4); // tile 4x4 across the surface
  }, [floorImage]);

  useMemo(() => {
    wallImage.wrapS = RepeatWrapping;
    wallImage.wrapT = RepeatWrapping;
    wallImage.repeat.set(4, 4); // tile 4x4 across the surface
  }, [wallImage]);

  if (getSelectedMaterialType === "Floor") {
    materials.floor.map = floorImage;
    materials.floor.needsUpdate = true;
  } else if (getSelectedMaterialType === "Wall") {
    materials.Walls.map = wallImage;
    materials.Walls.needsUpdate = true;
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh5_Color_5_0.geometry}
        material={materials.doors}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh5_Color_7_0.geometry}
        material={materials.Color_7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh5_Color_8_0.geometry}
        material={materials.Color_8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh5_img4_6_0.geometry}
        material={materials.img4_6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh6_Color_10_0.geometry}
        material={materials.CabinDoor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh6_Color_11_0.geometry}
        material={materials.Color_11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh6_Color_12_0.geometry}
        material={materials.Color_12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh6_Color_13_0.geometry}
        material={materials.CabinTop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh6_Color_14_0.geometry}
        material={materials.Color_14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh6_Color_15_0.geometry}
        material={materials.Color_15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh6_Color_9_0.geometry}
        material={materials.Color_9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh7_Color_10_0.geometry}
        material={materials.CabinDoor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh7_Color_14_0.geometry}
        material={materials.Color_14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh9_Color_16_0.geometry}
        material={materials.Color_16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh9_img10_17_0.geometry}
        material={materials.img10_17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_Color_21_0.geometry}
        material={materials.Color_21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img11_18_0.geometry}
        material={materials.img11_18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img12_19_0.geometry}
        material={materials.img12_19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img13_20_0.geometry}
        material={materials.img13_20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img14_22_0.geometry}
        material={materials.img14_22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img15_23_0.geometry}
        material={materials.img15_23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img16_24_0.geometry}
        material={materials.img16_24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img17_25_0.geometry}
        material={materials.img17_25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_0.geometry}
        material={materials.img18_26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_10_0.geometry}
        material={materials.img18_26_10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_11_0.geometry}
        material={materials.img18_26_11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_12_0.geometry}
        material={materials.img18_26_12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_13_0.geometry}
        material={materials.img18_26_13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_14_0.geometry}
        material={materials.img18_26_14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_15_0.geometry}
        material={materials.img18_26_15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_16_0.geometry}
        material={materials.img18_26_16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_17_0.geometry}
        material={materials.img18_26_17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_18_0.geometry}
        material={materials.img18_26_18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_19_0.geometry}
        material={materials.img18_26_19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_1_0.geometry}
        material={materials.img18_26_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_20_0.geometry}
        material={materials.img18_26_20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_21_0.geometry}
        material={materials.img18_26_21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_2_0.geometry}
        material={materials.img18_26_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_3_0.geometry}
        material={materials.img18_26_3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_4_0.geometry}
        material={materials.img18_26_4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_5_0.geometry}
        material={materials.img18_26_5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_6_0.geometry}
        material={materials.img18_26_6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_7_0.geometry}
        material={materials.img18_26_7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_8_0.geometry}
        material={materials.img18_26_8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img18_26_9_0.geometry}
        material={materials.img18_26_9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img19_27_0.geometry}
        material={materials.img19_27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img20_28_0.geometry}
        material={materials.img20_28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh10_img21_29_0.geometry}
        material={materials.img21_29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_14_0.geometry}
        material={materials.Color_14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_32_0.geometry}
        material={materials.Color_32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_33_0.geometry}
        material={materials.Color_33}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_37_0.geometry}
        material={materials.Color_37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_38_0.geometry}
        material={materials.Color_38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_39_0.geometry}
        material={materials.Color_39}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_41_0.geometry}
        material={materials.Color_41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_42_0.geometry}
        material={materials.Color_42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_Color_7_0.geometry}
        material={materials.Color_7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_img22_31_0.geometry}
        material={materials.img22_31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_img22_31_1_0.geometry}
        material={materials.img22_31_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_img23_34_0.geometry}
        material={materials.img23_34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_img24_35_0.geometry}
        material={materials.img24_35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_img25_36_0.geometry}
        material={materials.img25_36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_img26_40_0.geometry}
        material={materials.img26_40}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh12_img27_43_0.geometry}
        material={materials.img27_43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh13_img29_30_0.geometry}
        material={materials.counter}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh14_Color_44_0.geometry}
        material={materials.Color_44}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh15_Color_12_0.geometry}
        material={materials.Color_12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh15_Color_13_0.geometry}
        material={materials.CabinTop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh15_Color_15_0.geometry}
        material={materials.Color_15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh15_Color_45_0.geometry}
        material={materials.Color_45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh16_Color_10_0.geometry}
        material={materials.CabinDoor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh16_Color_14_0.geometry}
        material={materials.Color_14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh17_Color_13_0.geometry}
        material={materials.CabinTop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh17_Color_46_0.geometry}
        material={materials.Color_46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh2_img1_1_0.geometry}
        material={materials.Walls}
      >
        <Html position={[-17, 18, 10]}>
          <button onClick={() => setSelectedMaterialType("Wall")}>Wall</button>
        </Html>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh18_img5_48_0.geometry}
        material={materials.img5_48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh18_img5_48_1_0.geometry}
        material={materials.img5_48_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh18_img6_49_0.geometry}
        material={materials.img6_49}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh18_img7_47_0.geometry}
        material={materials.img7_47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh18_img7_47_1_0.geometry}
        material={materials.img7_47_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh19_Color_46_0.geometry}
        material={materials.Color_46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh20_Color_46_0.geometry}
        material={materials.Color_46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh20_Color_46_0001.geometry}
        material={materials.Color_46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh20_Color_46_0002.geometry}
        material={materials.Color_46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh20_Color_46_0003.geometry}
        material={materials.Color_46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh21_Color_10_0.geometry}
        material={materials.CabinDoor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh21_Color_13_0.geometry}
        material={materials.CabinTop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh22_Color_10_0.geometry}
        material={materials.CabinDoor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh22_Color_13_0.geometry}
        material={materials.CabinTop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh23_Color_50_0.geometry}
        material={materials.Color_50}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh24_img9_51_0.geometry}
        material={materials.img9_51}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh25_img9_51_0.geometry}
        material={materials.img9_51}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh26_img9_51_0.geometry}
        material={materials.img9_51}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh27_Color_12_0.geometry}
        material={materials.Color_12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh27_Color_13_0.geometry}
        material={materials.CabinTop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh27_Color_14_0.geometry}
        material={materials.Color_14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh27_Color_15_0.geometry}
        material={materials.Color_15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh27_Color_45_0.geometry}
        material={materials.Color_45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh28_Color_11_0.geometry}
        material={materials.Color_11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh28_Color_12_0.geometry}
        material={materials.Color_12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh28_Color_13_0.geometry}
        material={materials.CabinTop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh28_Color_14_0.geometry}
        material={materials.Color_14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh28_Color_15_0.geometry}
        material={materials.Color_15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh28_Color_52_0.geometry}
        material={materials.Color_52}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh28_Color_53_0.geometry}
        material={materials.Color_53}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh28_Color_9_0.geometry}
        material={materials.Color_9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh29_Color_12_0.geometry}
        material={materials.Color_12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh29_Color_54_0.geometry}
        material={materials.Color_54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh29_Color_55_0.geometry}
        material={materials.Color_55}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh4_img2_4_0.geometry}
        material={materials.floor}
      >
        <Html position={[0, 2, 0]}>
          <button onClick={() => setSelectedMaterialType("Floor")}>
            Floor
          </button>
        </Html>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/roomGlb.glb");
